version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Só a app é exposta para o host
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_example
      - SPRING_DATASOURCE_USERNAME=springuser
      - SPRING_DATASOURCE_PASSWORD=ThePassword

  mysql:
    image: mysql:8.0
    expose:
      - "3306"  # Visível apenas para os containers da mesma rede
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
